// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:background_siq/data/models/history_model.dart';
import 'package:background_siq/data/models/profile_model.dart';
import 'package:background_siq/data/models/recent_file_model.dart';
import 'package:background_siq/data/models/settings_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HistoryModelAdapter());
    registerAdapter(ProfileModelAdapter());
    registerAdapter(RecentFileModelAdapter());
    registerAdapter(SettingsModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HistoryModelAdapter());
    registerAdapter(ProfileModelAdapter());
    registerAdapter(RecentFileModelAdapter());
    registerAdapter(SettingsModelAdapter());
  }
}
